language: node_js

node_js:
  - "lts/*"

services:
  - docker

cache:
  directories:
    - node_modules

install:
  - npm install -q

script:
  - npm run build

after_script:
  - PACKAGE_VERSION=$(npm --loglevel silent run version)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $DOCKER_REPOSITORY:$PACKAGE_VERSION -t $DOCKER_REPOSITORY:latest .
  - docker push $DOCKER_REPOSITORY

branches:
  only:
    - master
